name: NHSHackday
markdown: redcarpet
pygments: true
previous:
    - Jan 2014 Cardiff
    - Nov 2013 Cambridge
    - May 2013 London
    - Jan 2013 Oxford
    - Sep 2012 Liverpool
    - May 2012 London
next-event:
    date: 24th-25th of May 2014
    location: "St.George's Students' Union, 2nd Floor Hunter Wing St George's, University of London, Cranmer Terrace, Tooting SW17 0RE"
    venue:  "St.George's Students' Union"
    signup: https://nhshackday.eventwax.com/nhs-hack-day-london/register
